name = "alexashing-portfolio"
compatibility_date = "2023-05-18"

[build]
command = "npm run build"
cwd = "."
watch_dir = "."

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }

# Pages configuration
pages_build_output_dir = "out"
